### ISSUE TITLE
Version control

### ISSUE THREAD

**Issue by favoyang** [Futuclass/EventBus#1]
Hi @skibitsky,

Thanks for contributing to the OpenUPM platform. You still need to create a GitHub release `vx.y.z` to make it work. After your GitHub release, our build pipelines will detect the changes and build UPM packages in 5-10 minutes. Then you can visit your package at https://openupm.com/packages/com.futuclass.event-bus/.

To make your life easier in the future,
- Managing release with CI: https://medium.com/openupm/how-to-maintain-upm-package-part-2-f352fbf5f87c
- Or managing release with CLI https://medium.com/openupm/how-to-maintain-upm-package-part-4-managing-package-release-with-cli-972ff5311163

**Comment by skibitsky** [comment]
Hi, @favoyang 

Thank you for the assistance! I've just made a release and can now see package available at OpenUPM 👍
